# Generated by Django 5.0.2 on 2024-03-14 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repuestosalinstante', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={},
        ),
        migrations.RemoveField(
            model_name='categoriaproducto',
            name='imagen',
        ),
    ]
