# Generated by Django 5.0.2 on 2024-03-17 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repuestosalinstante', '0002_alter_producto_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoriaProducto',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='año_lanzamiento',
        ),
    ]
