# Generated by Django 5.0.2 on 2024-03-17 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repuestosalinstante', '0003_delete_categoriaproducto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marca',
            old_name='país_origen',
            new_name='pais_origen',
        ),
    ]
